version: '3.2'

services:
  odoo:
    &odoo
    image: ${ODOO_IMAGE}:${ODOO_IMAGE_VERSION}
    volumes:
    - "${CONTAINER_VOLUME}/invoicing/odoo/extra-addons:/mnt/extra-addons:rw"
    - "./odoo/etc/:/etc/odoo:rw"
    ports:
    - "8069:8069"
    - "8070:8072"
    environment:
      USER: "${ODOO_POSTGRES_USER}"
      PASSWORD: "${ODOO_POSTGRES_PASSWORD}"
      HOST: ${DB_HOST:-db}
      DB_HOST: ${DB_HOST:-db}
    command: --max-cron-threads 0 --workers 8 --log-handler=:INFO
    restart: unless-stopped
    logging:
      driver: 'awslogs'
      options:
        awslogs-region: 'eu-west-2'
        awslogs-group: '/srv/logs/odoo.log'

  odoo-cron:
    << : *odoo
    ports: 
    - "8072"
    command: --max-cron-threads 8 --no-xmlrpc --database ${ODOO_CRON_DB}
    logging:
      driver: 'awslogs'
      options:
        awslogs-region: 'eu-west-2'
        awslogs-group: '/srv/logs/odoo-cron.log'